SET rightpass=haavapuu100
SET uudis1=See pakkfail asendatakse uue rakendusega
SET uudis2=Kiirrakendused on nd paremad kui kunagi varem
SET uudis3=M„lupulk on j„lle buutitav
SET uudis4=Markuse arvuti integratsioon on tagasi
SET uudis5=Taastasime vana Erti videod
SET u1=Markuse m„lupulk tuleb tagasi Seoses uue universaalse rakenduse loomisega Markuse m„lu- pulgale, pole enam vajadust uudiste pakkfaili jaoks. Selles uues rakenduses on uudised,   kiirprogrammid, videod, haldus ja abi. Lisaks on rakendus isikup„rastatav ja              salvestatavate s„tetega. Rakenduse arendamise ajaks j„„b see pakkfail alles ja arhiivsetelpähjustel ka p„rast valmimist.
SET u2=Nd on väimalik k„ivitada erinevaid rakendusi otse m„lupulgalt: ilma neid arvutisse      installimata. Ja see pole veel käik. Peagi saab neid rakendusi k„ivitada m„lupulga        haldamise rakendusega. Rohkem uudises nr. 1.
SET u3=Varem oli probleeme m„lupulga buutimisega, kus m„lupulk k„ivitas Windows 7 installeri.    Nd on see viga parandatud.
SET u4=Kas m„rkasite, et Markuse arvutis on nd ks ikoon all paremas nurgas? Nimelt Markuse    arvuti asjade logo. See on Markuse arvuti integratsioon. Kui te paremklikite on selles    erinevaid suvandeid. Uueks valikuks on ””reØiim ja peo k„ivitamine. Lisaks ilmub unikaalneprogrammide laadimise ekraan igal sisselogimisel. T„nu sellele, laadib arvuti programme   effektiivsemalt ja seetättu on arvuti protsessi j„rel koheselt kasutamiseks valmis.
SET u5=Taastasime Markuse vanast arvutist edukalt video nimega Ert 100. Tegu on vana videoga, kusn„idatakse erinevaid asju, mida ei saa selgitada. Lisaks rekonstrueerisin väimaliku Ert   2011 video, millest osa oli selles Ert 100 videos.
SET video1=Markuse asjad 2017.ogv
SET video2=Kas maal väi maal.wmv
SET video3=Markus Maal - l„bi nende aastate.wmv
SET selectedcol=07
SET adapp=
SET adpp=
SET ads=n
SET adtext=
